CREATE TABLE AGNS AS
    -- Generate the NED clusters --
    WITH NED_AGNS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_NED.UID FROM XREF_NED WHERE XREF_NED.Type IN ('QGroup', 'QSO', 'Q_Lens') )
    ),
    -- Generate the SIMBAD clusters --
    SIMBAD_AGNS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_SIMBAD.UID FROM XREF_SIMBAD WHERE XREF_SIMBAD.UID IN ('AGN', 'SyG', 'Sy1', 'Sy2', 'rG', 'LIN', 'QSO', 'Bla', 'BLL', 'AG?', 'Q?', 'Bz?', 'BL?') )
    )
    -- Generate the full table --
    SELECT * FROM eROSITA WHERE (eROSITA.UID IN (SELECT NED_AGNS.UID FROM NED_AGNS)) OR (eROSITA.UID IN (SELECT SIMBAD_AGNS.UID FROM SIMBAD_AGNS))
