CREATE TABLE GCLSTR AS
    -- Generate the NED clusters --
    WITH NED_CLSTRS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_NED.UID FROM XREF_NED WHERE XREF_NED.Type IN ('GClstr', 'GGroup', 'GPair', 'GTrpl') )
    ),
    -- Generate the SIMBAD clusters --
    SIMBAD_CLSTRS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_SIMBAD.UID FROM XREF_SIMBAD WHERE XREF_SIMBAD.UID IN ('IG', 'PaG', 'GrG', 'CGG', 'ClG', 'C?G', 'PCG?', 'SC?', 'PCG', 'SCG') )
    )
    -- Generate the full table --
    SELECT * FROM eROSITA WHERE (eROSITA.UID IN (SELECT NED_CLSTRS.UID FROM NED_CLSTRS)) OR (eROSITA.UID IN (SELECT SIMBAD_CLSTRS.UID FROM SIMBAD_CLSTRS))
