CREATE TABLE SNRS AS
    -- Generate the NED clusters --
    WITH NED_SNRS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_NED.UID FROM XREF_NED WHERE XREF_NED.Type IN ('Nova', 'SN', 'SNR', '!Nova', '!SN', '!SNR') )
    ),
    -- Generate the SIMBAD clusters --
    SIMBAD_SNRS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_SIMBAD.UID FROM XREF_SIMBAD WHERE XREF_SIMBAD.UID IN ('SNR', 'SR?', 'SN*', 'SN?') )
    )
    -- Generate the full table --
    SELECT * FROM eROSITA WHERE (eROSITA.UID IN (SELECT NED_SNRS.UID FROM NED_SNRS)) OR (eROSITA.UID IN (SELECT SIMBAD_SNRS.UID FROM SIMBAD_SNRS))
