CREATE TABLE EXOTS AS
    -- Generate the NED clusters --
    WITH NED_EXOTS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_NED.UID FROM XREF_NED WHERE XREF_NED.Type IN ('XrayS', 'Psr') )
    ),
    -- Generate the SIMBAD clusters --
    SIMBAD_EXOTS AS (
        SELECT * FROM eROSITA WHERE eROSITA.UID IN (SELECT XREF_SIMBAD.UID FROM XREF_SIMBAD WHERE XREF_SIMBAD.UID IN ('X', 'ULX', 'UX?', 'BH', 'GWE', 'XB*', 'LXB', 'HXB', 'CV*') )
    )
    -- Generate the full table --
    SELECT * FROM eROSITA WHERE (eROSITA.UID IN (SELECT NED_EXOTS.UID FROM NED_EXOTS)) OR (eROSITA.UID IN (SELECT SIMBAD_EXOTS.UID FROM SIMBAD_EXOTS))
