#!/usr/bin/bash
CALLSIG=$1 # the base call signature.
HEADER="\x1b[33;49m[\x1b[31;49mpyROS XREF\x1b[33;49m]\x1b[39;49m: "

if [ "$CALLSIG" = "build" ]; then
  echo "${@:2}"
  pyrosXREF_build "${@:2}"

elif [ "$CALLSIG" = "add" ]; then

  if [ "$2" = "cat" ]; then
    pyrosXREF_addcat "${@:3}"

  elif [ "$2" = "sort" ]; then
    pyrosXREF_addsort "${@:3}"

  else
    exit 1
  fi

elif [ "$CALLSIG" = "" ]; then
  echo -e "$HEADER [\x1b[35mERROR\x1b[0m] pyrosXREF must be followed by a valid command."

else
  echo -e "$HEADER [\x1b[35mERROR\x1b[0m] $CALLSIG is not a valid command."
  exit 1
fi
