#!/usr/bin/env python

# ==================================================================================================================== #
# Generate the XREF database for a given catalog.                                                                      #
# ==================================================================================================================== #
import os
import pathlib as pt
from argparse import ArgumentParser
from pyROS.utils import mylog
from pyROS.erosita.catalogs import eROSITACatalog

parser = ArgumentParser()
parser.add_argument("database_path", type=str, help="The path at which to generate the database file.")
parser.add_argument("catalog_path",type=str ,help="The path to the valid catalog.")
parser.add_argument("-n","--number",type=int, help="The number of objects in the catalog to XREF.")
parser.add_argument("-d","--databases",default="all",nargs="+",help="The databases to XREF against.")
parser.add_argument("--group_size", type=int, help="Max group size", default=20)
parser.add_argument("--nthreads", type=int, help="Number of threads", default=1)
parser.add_argument("--catalog_type",type=str,help="The catalog format",default="eRASS1")
parser.add_argument("-o","--overwrite",action="store_true")
args = parser.parse_args()

# Setup
#------#
catalog = eROSITACatalog(args.catalog_path,format="fits",catalog_type=args.catalog_type)

catalog.xref(args.database_path,groupsize=args.group_size,maxthreads=args.nthreads,included_databases=args.databases,overwrite=args.overwrite)